import {
  Activity,
  AtSign,
  BadgeCheck,
  CalendarCheck,
  ChartLine,
  ClipboardList,
  CloudUpload,
  Cpu,
  Database,
  Factory,
  FileLock,
  FileText,
  Gem,
  Globe,
  GraduationCap,
  Handshake,
  Headset,
  Hospital,
  Hotel,
  KeyRound,
  Landmark,
  Layers,
  LifeBuoy,
  Lightbulb,
  Lock,
  Mail,
  MailCheck,
  MapPin,
  Network,
  Phone,
  RefreshCw,
  Rocket,
  RotateCcw,
  Scale,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Target,
  Truck,
  UserCheck,
  UserCog,
  Users,
  Wifi,
  Zap,
  type LucideProps,
} from 'lucide-react';

/** Mapa central de ícones — os arquivos de dados referenciam ícones por estas chaves. */
const icons = {
  activity: Activity,
  at: AtSign,
  badge: BadgeCheck,
  calendarCheck: CalendarCheck,
  chart: ChartLine,
  clipboard: ClipboardList,
  cloudUpload: CloudUpload,
  cpu: Cpu,
  database: Database,
  factory: Factory,
  fileShield: FileLock,
  fileText: FileText,
  gem: Gem,
  globe: Globe,
  graduation: GraduationCap,
  handshake: Handshake,
  headset: Headset,
  hospital: Hospital,
  hotel: Hotel,
  keyRound: KeyRound,
  landmark: Landmark,
  layers: Layers,
  lifeBuoy: LifeBuoy,
  lightbulb: Lightbulb,
  lock: Lock,
  mail: Mail,
  mailCheck: MailCheck,
  mapPin: MapPin,
  network: Network,
  phone: Phone,
  refresh: RefreshCw,
  rocket: Rocket,
  rotateCcw: RotateCcw,
  scale: Scale,
  server: Server,
  settings: Settings,
  shield: Shield,
  shieldCheck: ShieldCheck,
  cart: ShoppingCart,
  sliders: SlidersHorizontal,
  target: Target,
  truck: Truck,
  userCheck: UserCheck,
  userCog: UserCog,
  users: Users,
  wifi: Wifi,
  zap: Zap,
} as const;

export type IconName = keyof typeof icons;

export function Icon({ name, ...props }: { name: IconName } & LucideProps) {
  const Cmp = icons[name];
  return <Cmp aria-hidden="true" focusable="false" strokeWidth={1.75} {...props} />;
}
