import {
  ArchiveRestore,
  BrickWall,
  Building,
  Cable,
  Cloud,
  DatabaseBackup,
  FileChartColumn,
  FileCheck,
  Funnel,
  Gauge,
  HardDrive,
  Info,
  MonitorSmartphone,
  Play,
  Settings2,
  Timer,
  UserLock,
  Workflow,
  Wrench,
  Activity,
  AtSign,
  BadgeCheck,
  CalendarCheck,
  ChartLine,
  ClipboardList,
  CloudUpload,
  Cpu,
  Database,
  Factory,
  FileLock,
  FileText,
  Gem,
  Globe,
  GraduationCap,
  Handshake,
  Headset,
  Hospital,
  Hotel,
  KeyRound,
  Landmark,
  Layers,
  LifeBuoy,
  Lightbulb,
  Lock,
  Mail,
  MailCheck,
  MapPin,
  Network,
  Phone,
  RefreshCw,
  Rocket,
  RotateCcw,
  Scale,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Target,
  Truck,
  UserCheck,
  UserCog,
  Users,
  Wifi,
  Zap,
  type LucideProps,
} from 'lucide-react';

/** Mapa central de ícones — os arquivos de dados referenciam ícones por estas chaves. */
const icons = {
  archiveRestore: ArchiveRestore,
  brickWall: BrickWall,
  building: Building,
  cable: Cable,
  cloud: Cloud,
  databaseBackup: DatabaseBackup,
  fileChart: FileChartColumn,
  fileCheck: FileCheck,
  funnel: Funnel,
  gauge: Gauge,
  hardDrive: HardDrive,
  info: Info,
  devices: MonitorSmartphone,
  play: Play,
  settingsCog: Settings2,
  timer: Timer,
  userLock: UserLock,
  workflow: Workflow,
  wrench: Wrench,
  activity: Activity,
  at: AtSign,
  badge: BadgeCheck,
  calendarCheck: CalendarCheck,
  chart: ChartLine,
  clipboard: ClipboardList,
  cloudUpload: CloudUpload,
  cpu: Cpu,
  database: Database,
  factory: Factory,
  fileShield: FileLock,
  fileText: FileText,
  gem: Gem,
  globe: Globe,
  graduation: GraduationCap,
  handshake: Handshake,
  headset: Headset,
  hospital: Hospital,
  hotel: Hotel,
  keyRound: KeyRound,
  landmark: Landmark,
  layers: Layers,
  lifeBuoy: LifeBuoy,
  lightbulb: Lightbulb,
  lock: Lock,
  mail: Mail,
  mailCheck: MailCheck,
  mapPin: MapPin,
  network: Network,
  phone: Phone,
  refresh: RefreshCw,
  rocket: Rocket,
  rotateCcw: RotateCcw,
  scale: Scale,
  server: Server,
  settings: Settings,
  shield: Shield,
  shieldCheck: ShieldCheck,
  cart: ShoppingCart,
  sliders: SlidersHorizontal,
  target: Target,
  truck: Truck,
  userCheck: UserCheck,
  userCog: UserCog,
  users: Users,
  wifi: Wifi,
  zap: Zap,
} as const;

export type IconName = keyof typeof icons;

export const iconNames = Object.keys(icons).sort() as IconName[];

export const isIconName = (name: string): name is IconName => Object.prototype.hasOwnProperty.call(icons, name);

/** Aceita nomes vindos do painel/API; nomes desconhecidos usam o ícone "building". */
export function Icon({ name, ...props }: { name: IconName | string } & LucideProps) {
  const Cmp = icons[isIconName(name) ? name : 'building'];
  return <Cmp aria-hidden="true" focusable="false" strokeWidth={1.75} {...props} />;
}
